---
title: "Drafting"
author: "we are all eric."
date: "9/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F, warning = F, include=F}
source("R/convenience.R")
source("R/cleaning.R")
watersystems <- fetch_water_service_areas()
schools <- fetch_active_public_schools()
analyses <- fetch_water_quality_analyses()
```

```{r}
a <- systems %$% unique(system_id) %>% sort()
length(a)

b <- watersystems %$% unique(region_id) %>% sort()
length(b)

d <- intersect(a, b)
length(d)
```
```{r}
geo_matched <- geo_join(schools, watersystems, 'Longitude', 'Latitude')
1 - (geo_matched %$% mean(is.na(region_id)))
1 - (geo_matched %>% filter(EILCode == "ELEM") %$% mean(is.na(region_id)))
```
```{r}
water <- merge_water_data(watersystems, schools, analyses)
View(summarize_water_data(water, retain_geometry = F))
water %>% get_nested_column("4210006", analyses) -> analysis; View(analysis)

get_school_jointable(water)
```




```{r}
ca_map <- 
  maps::map("state", regions = "california", plot = F, fill = T) %>% 
  sf::st_as_sf()
watersystems %>%
  ggplot(aes(fill = population)) +
  geom_sf() #+geom_sf(data = ca_map)
```

```{r}
tic("Entire Run")
source("R/convenience.R")
source("R/cleaning.R")
source("R/email.R")

tic("Fetching data")
tic("Fetching watersystems")
watersystems <- fetch_water_service_areas()
toc()
tic("Fetching schools")
schools <- fetch_active_public_schools()
toc()
tic("Fetching water quality samples")
analyses <- fetch_water_quality_analyses()
toc()
toc()

tic("Merging watersystems, schools, and chemical samples")
water <- merge_water_data(watersystems, schools, analyses)
toc()

tic("Email Body Generation")
emails <- generate_content(water)
toc()

tic("Email Sending")
send_emails(emails, dry_run = T)
toc()
toc()
```

```{r}
tic("Entire Run")
source("R/convenience.R")
source("R/cleaning.R")
source("R/email.R")

tic("Fetching data")
tic("Fetching watersystems")
watersystems <- fetch_water_service_areas()
toc()
tic("Fetching schools")
schools <- fetch_active_public_schools()
toc()
tic("Fetching water quality samples")
analyses <- fetch_water_quality_analyses()
toc()
toc()

tic("Merging watersystems, schools, and chemical samples")
water <- merge_water_data(watersystems, schools, analyses)
toc()

tic("Sending Emails")
send_batch_email(water, dry_run = T)
toc()
```

```{r}
s <- summarize_water_data(water, F)

s %>% 
  filter(`Offending Chemical over MCL` != "LEAD", `Highest Percentage over MCL` > 0, `Highest Percentage over MCL` < 1500) %>%
  mutate(system_id = fct_reorder(system_id, -`Highest Percentage over MCL`), `Highest Percentage over MCL` = `Highest Percentage over MCL` / 100) %>%
  ggplot(aes(system_id, `Highest Percentage over MCL`, fill = `Offending Chemical over MCL`)) +
  geom_col() +
  scale_y_continuous(breaks = seq(0, 10, by = 1), labels = scales::percent) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Greatest MCL Violations, by Region, since January 2017",
       subtitle = "Lead not considered in this display.",
       y = "% over MCL", x = "Public Water System Region")

s %>% 
  filter(`Proportion of Chemicals over MCL` > .3) %>%
  mutate(system_id = fct_reorder(system_id, -`Proportion of Chemicals over MCL`)) %>%
  ggplot(aes(system_id, `Proportion of Chemicals over MCL`, fill = `Number of Schools`)) +
  geom_col() +
  scale_y_continuous(breaks = seq(0, 1, by = .1), labels = scales::percent) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Average MCL Violation Rate by Region, since January 2017",
       subtitle = "MCL Violation Rate given by proportion of water samples with results exceeding MCL since January 2017.",
       y = "MCL Violation Rate", x = "Public Water System Region",
       caption = "Only most dangerous chemicals and turbidity considered.")
```


